name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main  # 或者您希望触发部署的其他分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout
        uses: actions/checkout@v2

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'  # 替换为您希望使用的 Flutter 版本

      - name: Create web application
        run: flutter create --platform=web example
      
      # 获取 Flutter 依赖
      - name: Install dependencies
        run: cd example && flutter pub get

      # 构建 Flutter Web 应用
      - name: Build Flutter Web
        run: cd example && flutter build web --release

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
